language: go
go_import_path: github.com/dicot-project/dicot-api
sudo: false
dist: trusty

go:
- 1.8
- 1.9

install:
 - git reset --hard
 - go get github.com/golang/dep/cmd/dep

script:
 - make
 - make check

cache:
  directories:
  - vendor

notifications:
  irc:
    # The channel name "irc.freenode.net#dicot" is encrypted against dicot-project/dicot-api
    # to prevent IRC notifications from github forks. This was created using:
    # $ travis encrypt -r "dicot-project/dicot-api" "irc.freenode.net#dicot"
    channels:
      - secure: "QbzHdmjCKLdIQUMZ6aA23hNdXMhSPRjpcHJ4u/1E6sQuRtd2C0ARVQQv3cNt+c71n6x3gwFvCInXjZ6Vpq5bOHme9V9CyFqefak/DVoFnqAzgU1JgmCBVf9MBGpv00rbzHoHV1aYLwsavZOJLMFF6aFjmvsr5sHrzZPKxdfSqZP+W3vyAzXUogwJbzxWNK8FYlf8exYNn7JoWmF6RLMxAXeAz3SIth/uHQtblW9KuWngjWhc/KCPusDaEHWqQUrEt3UasrZ5Lw10Q5NHD31o24HJiTdd7haq2fMiZs0P/A1wbU7/pCQhO5GkhUVp/2FtoYq0zzitzyWuf1lkEKY0fzsk2BGD/6pQq1dCbc9flMhruTemcpu8+SJmjQwcPYEPsk/KFvvT1jHUqK8eeBY6xfBIsqsXJWA8k414hJVQRwvk1hYMlBqaG2Z8ZV0gOJ84R6XxMSyvZ7iw9ns7/FecnyX+smQmE9mhyy0RseLh/nft0cCG99ADlOwTE9sqciWl1z3D9R1hvKloxNlg+ikuKbeKNuGC0qO7zI9F8o4d7ksTCg+0hAYKeGWvCdmrk0KtwLZ91MdK2T68XPVJIGmOUO8qPzlPPGtAdmhxZj4QpAgy5SALTPhGfiiTklIKP35mRh0hVvCyaggurP7wzS28oDFOLuYAW8rDH1kvb6vl9A=="
    on_success: change
    on_failure: always
